public with sharing class PrimitiveDataTypeDemo {
     public void Demo(){
        system.debug('Hello');
     }

    public void printBasicDataType2()
    {
        object ob1 = 'string datatype in object';
        object ob2 = 77;
        object ob3 = true;
        system.debug(ob1);
        system.debug(ob2);
        system.debug(ob3);
        id accId = '00000111ww333';
        system.debug('acc id is'+ accId);
    }
}
