public class StudentDetails {
    public void nameOfStudent() {
       
      string myName = 'SelGul';
      system.debug('My name is ' + myName);
      
      string placeOfBirth = 'Turkey';
      system.debug('I was born in  ' + placeOfBirth);

      string myHobby = 'walking, running';
       system.debug('I like  ' + myHobby);

       string placeOfVisit = ' New York, Colorado, Texas, Canada';
       system.debug('I like to visit  ' + placeOfVisit);

    }
}
