Calculator problems = new Calculator();
//problems.dynamicCalculationMethod(10,67.5,'addition');
system.debug(problems.dynamicCalculationMethod(10,67.5,'addition'));
problems.dynamicCalculationMethod(10,67.5,'subtraction');
system.debug(problems.dynamicCalculationMethod(90,60,'subtraction'));
problems.dynamicCalculationMethod(8,2,'division');
system.debug(problems.dynamicCalculationMethod(8,2,'division'));
problems.dynamicCalculationMethod(6,4,'multiplication');
system.debug(problems.dynamicCalculationMethod(6,4,'multiplication'));
