
DmlDemo.dmlUpdateMultiple_right_2();
DmlDemo.dmlInsertDemo_stndObj();
DmlDemo.dmlInsertDemo_cstmObj();
DmlDemo.dmlUpdatetDemo();
DmlDemo.dmlUpdatetDemo_3();
DmlDemo.dmlInsertDemo_4();
DmlDemo.dmlInsertDemo_5();
DmlDemo.dmlInsertMultiple_right();

 //List<account> listAccount = [select id from account where createddate =THIS_WEEK];
 //delete listAccount; or 
 delete[select id from account where createddate =THIS_WEEK];